const products = [
    {
        name: "T-Rex Prime Burger",
        description: "T-Rex Prime Burger e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da strato di carne succosa con bordo croccante e continua con cheddar fuso e cipolla glassata. La ricetta non copia altri articoli: qui la priorita e ideato per mantenere calore e texture per tutto il servizio, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria burgers. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, T-Rex Prime Burger e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 11.90,
        geological_era: "Late Jurassic",
        slug: "t-rex-prime-burger",
    },
    {
        name: "Raptor Double Smash",
        description: "Raptor Double Smash e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da strato di carne succosa con bordo croccante e continua con cheddar fuso e cipolla glassata. La ricetta non copia altri articoli: qui la priorita e ideato per mantenere calore e texture per tutto il servizio, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria burgers. In fascia pranzo, mantiene un ritmo alto di uscita senza perdere precisione sensoriale. L immaginario e quello delle grandi pianure mesozoiche, con un profilo aromatico ampio ma controllato. Dal punto di vista operativo, Raptor Double Smash e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 12.45,
        geological_era: "Late Jurassic",
        slug: "raptor-double-smash",
    },
    {
        name: "Stego Crunch Burger",
        description: "Stego Crunch Burger e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da doppia piastrata di carne e continua con maionese pepata e lattuga croccante. La ricetta non copia altri articoli: qui la priorita e pensato per chi vuole un morso potente ma pulito, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria burgers. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Stego Crunch Burger e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 13.00,
        geological_era: "Late Jurassic",
        slug: "stego-crunch-burger",
    },
    {
        name: "Bronto Tower Burger",
        description: "Bronto Tower Burger e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da strato di carne succosa con bordo croccante e continua con cheddar fuso e cipolla glassata. La ricetta non copia altri articoli: qui la priorita e ideato per mantenere calore e texture per tutto il servizio, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria burgers. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Bronto Tower Burger e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 13.55,
        geological_era: "Late Jurassic",
        slug: "bronto-tower-burger",
    },
    {
        name: "Cretaceous Classic Burger",
        description: "Cretaceous Classic Burger e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da doppia piastrata di carne e continua con maionese pepata e lattuga croccante. La ricetta non copia altri articoli: qui la priorita e pensato per chi vuole un morso potente ma pulito, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria burgers. In fascia pranzo, mantiene un ritmo alto di uscita senza perdere precisione sensoriale. L immaginario e quello delle grandi pianure mesozoiche, con un profilo aromatico ampio ma controllato. Dal punto di vista operativo, Cretaceous Classic Burger e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 14.10,
        geological_era: "Late Jurassic",
        slug: "cretaceous-classic-burger",
    },
    {
        name: "Raptor Crispy Bites",
        description: "Raptor Crispy Bites e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da morsi rapidi dal taglio netto e sapido e continua con abbinati a salsa intensa e tocco speziato. La ricetta non copia altri articoli: qui la priorita e funzionano bene in combo e menu famiglia, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria bites. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Raptor Crispy Bites e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 6.90,
        geological_era: "Early Cretaceous",
        slug: "raptor-crispy-bites",
    },
    {
        name: "Triassic Chicken Nuggets",
        description: "Triassic Chicken Nuggets e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da morsi rapidi dal taglio netto e sapido e continua con abbinati a salsa intensa e tocco speziato. La ricetta non copia altri articoli: qui la priorita e funzionano bene in combo e menu famiglia, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria bites. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Triassic Chicken Nuggets e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 7.45,
        geological_era: "Early Cretaceous",
        slug: "triassic-chicken-nuggets",
    },
    {
        name: "Compsognathus Mini Bites",
        description: "Compsognathus Mini Bites e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da pezzi piccoli panati con cuore morbido e continua con perfetti da intingere in condimenti cremosi. La ricetta non copia altri articoli: qui la priorita e la presa e comoda e il formato e da snack tecnico, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria bites. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Compsognathus Mini Bites e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 8.00,
        geological_era: "Early Cretaceous",
        slug: "compsognathus-mini-bites",
    },
    {
        name: "Meteor Pop Bites",
        description: "Meteor Pop Bites e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da morsi rapidi dal taglio netto e sapido e continua con abbinati a salsa intensa e tocco speziato. La ricetta non copia altri articoli: qui la priorita e funzionano bene in combo e menu famiglia, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria bites. In fascia pranzo, mantiene un ritmo alto di uscita senza perdere precisione sensoriale. L immaginario e quello delle grandi pianure mesozoiche, con un profilo aromatico ampio ma controllato. Dal punto di vista operativo, Meteor Pop Bites e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 8.55,
        geological_era: "Early Cretaceous",
        slug: "meteor-pop-bites",
    },
    {
        name: "Jurassic Pepper Bites",
        description: "Jurassic Pepper Bites e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da morsi rapidi dal taglio netto e sapido e continua con abbinati a salsa intensa e tocco speziato. La ricetta non copia altri articoli: qui la priorita e funzionano bene in combo e menu famiglia, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria bites. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Jurassic Pepper Bites e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 9.10,
        geological_era: "Early Cretaceous",
        slug: "jurassic-pepper-bites",
    },
    {
        name: "Ptero Fresh Wrap",
        description: "Ptero Fresh Wrap e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da struttura avvolta che unisce componente sapida e vegetale e continua con chiusura cremosa con salsa dedicata. La ricetta non copia altri articoli: qui la priorita e ottimo in asporto grazie alla forma compatta, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria wraps. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Ptero Fresh Wrap e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 8.40,
        geological_era: "Middle Jurassic",
        slug: "ptero-fresh-wrap",
    },
    {
        name: "Savanna Smoke Wrap",
        description: "Savanna Smoke Wrap e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da struttura avvolta che unisce componente sapida e vegetale e continua con chiusura cremosa con salsa dedicata. La ricetta non copia altri articoli: qui la priorita e ottimo in asporto grazie alla forma compatta, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria wraps. In fascia pranzo, mantiene un ritmo alto di uscita senza perdere precisione sensoriale. L immaginario e quello delle grandi pianure mesozoiche, con un profilo aromatico ampio ma controllato. Dal punto di vista operativo, Savanna Smoke Wrap e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 8.95,
        geological_era: "Middle Jurassic",
        slug: "savanna-smoke-wrap",
    },
    {
        name: "Fossil Ranch Wrap",
        description: "Fossil Ranch Wrap e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da struttura avvolta che unisce componente sapida e vegetale e continua con chiusura cremosa con salsa dedicata. La ricetta non copia altri articoli: qui la priorita e ottimo in asporto grazie alla forma compatta, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria wraps. In fascia pranzo, mantiene un ritmo alto di uscita senza perdere precisione sensoriale. L immaginario e quello delle grandi pianure mesozoiche, con un profilo aromatico ampio ma controllato. Dal punto di vista operativo, Fossil Ranch Wrap e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 9.50,
        geological_era: "Middle Jurassic",
        slug: "fossil-ranch-wrap",
    },
    {
        name: "Volcanic Spicy Wrap",
        description: "Volcanic Spicy Wrap e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da piadina arrotolata con cuore caldo e strati freschi e continua con equilibrio tra croccante e morbido in ogni morso. La ricetta non copia altri articoli: qui la priorita e facile da mangiare in pausa pranzo veloce, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria wraps. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Volcanic Spicy Wrap e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 10.05,
        geological_era: "Middle Jurassic",
        slug: "volcanic-spicy-wrap",
    },
    {
        name: "Herbivore Balance Wrap",
        description: "Herbivore Balance Wrap e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da struttura avvolta che unisce componente sapida e vegetale e continua con chiusura cremosa con salsa dedicata. La ricetta non copia altri articoli: qui la priorita e ottimo in asporto grazie alla forma compatta, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria wraps. In fascia pranzo, mantiene un ritmo alto di uscita senza perdere precisione sensoriale. L immaginario e quello delle grandi pianure mesozoiche, con un profilo aromatico ampio ma controllato. Dal punto di vista operativo, Herbivore Balance Wrap e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 10.60,
        geological_era: "Middle Jurassic",
        slug: "herbivore-balance-wrap",
    },
    {
        name: "Lava Fries",
        description: "Lava Fries e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da porzione di supporto dal gusto netto e continua con chiusura pulita che prepara il morso successivo. La ricetta non copia altri articoli: qui la priorita e utile per completare menu ad alta soddisfazione, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sides. Sul banco caldo, la resa rimane costante e riconoscibile dal primo all ultimo pezzo. L identita Jurassic e costruita con dettaglio, cosi ogni assaggio comunica subito appartenenza al brand. Dal punto di vista operativo, Lava Fries e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 4.50,
        geological_era: "Late Cretaceous",
        slug: "lava-fries",
    },
    {
        name: "Dino Onion Rings",
        description: "Dino Onion Rings e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da accompagnamento saporito e immediato e continua con sale bilanciato e speziatura leggera. La ricetta non copia altri articoli: qui la priorita e regge bene tempi di consegna e consumo, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sides. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Dino Onion Rings e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 5.05,
        geological_era: "Late Cretaceous",
        slug: "dino-onion-rings",
    },
    {
        name: "Canyon Potato Wedges",
        description: "Canyon Potato Wedges e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da contorno croccante con cottura calibrata e continua con profilo aromatico semplice ma riconoscibile. La ricetta non copia altri articoli: qui la priorita e perfetto con burger robusti e wrap leggeri, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sides. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Canyon Potato Wedges e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 5.60,
        geological_era: "Late Cretaceous",
        slug: "canyon-potato-wedges",
    },
    {
        name: "Jurassic Coleslaw Cup",
        description: "Jurassic Coleslaw Cup e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da contorno croccante con cottura calibrata e continua con profilo aromatico semplice ma riconoscibile. La ricetta non copia altri articoli: qui la priorita e perfetto con burger robusti e wrap leggeri, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sides. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Jurassic Coleslaw Cup e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 6.15,
        geological_era: "Late Cretaceous",
        slug: "jurassic-coleslaw-cup",
    },
    {
        name: "Cretaceous Corn Bites",
        description: "Cretaceous Corn Bites e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da accompagnamento saporito e immediato e continua con sale bilanciato e speziatura leggera. La ricetta non copia altri articoli: qui la priorita e regge bene tempi di consegna e consumo, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sides. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Cretaceous Corn Bites e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 6.70,
        geological_era: "Late Cretaceous",
        slug: "cretaceous-corn-bites",
    },
    {
        name: "Amber BBQ Sauce",
        description: "Amber BBQ Sauce e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da salsa densa dal colore intenso e continua con migliora la succosita percepita. La ricetta non copia altri articoli: qui la priorita e dosata per restare netta ma non invasiva, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sauces. Sul banco caldo, la resa rimane costante e riconoscibile dal primo all ultimo pezzo. L identita Jurassic e costruita con dettaglio, cosi ogni assaggio comunica subito appartenenza al brand. Dal punto di vista operativo, Amber BBQ Sauce e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 1.50,
        geological_era: "Mesozoic Blend",
        slug: "amber-bbq-sauce",
    },
    {
        name: "Raptor Hot Sauce",
        description: "Raptor Hot Sauce e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da blend aromatico a impatto immediato e continua con apre il gusto e allunga il finale. La ricetta non copia altri articoli: qui la priorita e pensata per intingere o rifinire, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sauces. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Raptor Hot Sauce e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 2.05,
        geological_era: "Mesozoic Blend",
        slug: "raptor-hot-sauce",
    },
    {
        name: "Fossil Mayo Sauce",
        description: "Fossil Mayo Sauce e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da blend aromatico a impatto immediato e continua con apre il gusto e allunga il finale. La ricetta non copia altri articoli: qui la priorita e pensata per intingere o rifinire, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sauces. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Fossil Mayo Sauce e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 2.60,
        geological_era: "Mesozoic Blend",
        slug: "fossil-mayo-sauce",
    },
    {
        name: "Smoky Tar Sauce",
        description: "Smoky Tar Sauce e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da salsa densa dal colore intenso e continua con migliora la succosita percepita. La ricetta non copia altri articoli: qui la priorita e dosata per restare netta ma non invasiva, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sauces. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Smoky Tar Sauce e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 3.15,
        geological_era: "Mesozoic Blend",
        slug: "smoky-tar-sauce",
    },
    {
        name: "Meteor Honey Mustard",
        description: "Meteor Honey Mustard e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da blend aromatico a impatto immediato e continua con apre il gusto e allunga il finale. La ricetta non copia altri articoli: qui la priorita e pensata per intingere o rifinire, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria sauces. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Meteor Honey Mustard e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 3.70,
        geological_era: "Mesozoic Blend",
        slug: "meteor-honey-mustard",
    },
    {
        name: "Glacier Cola",
        description: "Glacier Cola e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da proposta liquida con carattere immediato e continua con dolcezza presente ma non eccessiva. La ricetta non copia altri articoli: qui la priorita e coerente con servizio veloce e continuo, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria drinks. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Glacier Cola e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 3.20,
        geological_era: "Quaternary Service",
        slug: "glacier-cola",
    },
    {
        name: "Jurassic Lemon Soda",
        description: "Jurassic Lemon Soda e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da mix equilibrato per accompagnare sapori intensi e continua con carbonazione o cremosita ben controllata. La ricetta non copia altri articoli: qui la priorita e ottimo in formato take away, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria drinks. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Jurassic Lemon Soda e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 3.75,
        geological_era: "Quaternary Service",
        slug: "jurassic-lemon-soda",
    },
    {
        name: "Triassic Mango Shake",
        description: "Triassic Mango Shake e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da mix equilibrato per accompagnare sapori intensi e continua con carbonazione o cremosita ben controllata. La ricetta non copia altri articoli: qui la priorita e ottimo in formato take away, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria drinks. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Triassic Mango Shake e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 4.30,
        geological_era: "Quaternary Service",
        slug: "triassic-mango-shake",
    },
    {
        name: "Bronto Vanilla Milk",
        description: "Bronto Vanilla Milk e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da mix equilibrato per accompagnare sapori intensi e continua con carbonazione o cremosita ben controllata. La ricetta non copia altri articoli: qui la priorita e ottimo in formato take away, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria drinks. Sul banco caldo, la resa rimane costante e riconoscibile dal primo all ultimo pezzo. L identita Jurassic e costruita con dettaglio, cosi ogni assaggio comunica subito appartenenza al brand. Dal punto di vista operativo, Bronto Vanilla Milk e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 4.85,
        geological_era: "Quaternary Service",
        slug: "bronto-vanilla-milk",
    },
    {
        name: "Cretaceous Iced Tea",
        description: "Cretaceous Iced Tea e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da mix equilibrato per accompagnare sapori intensi e continua con carbonazione o cremosita ben controllata. La ricetta non copia altri articoli: qui la priorita e ottimo in formato take away, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria drinks. Sul banco caldo, la resa rimane costante e riconoscibile dal primo all ultimo pezzo. L identita Jurassic e costruita con dettaglio, cosi ogni assaggio comunica subito appartenenza al brand. Dal punto di vista operativo, Cretaceous Iced Tea e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 5.40,
        geological_era: "Quaternary Service",
        slug: "cretaceous-iced-tea",
    },
    {
        name: "Fossil Cookie Pie",
        description: "Fossil Cookie Pie e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da dolce da fine pasto con struttura morbida e continua con aroma avvolgente con finale persistente. La ricetta non copia altri articoli: qui la priorita e perfetto dopo portate salate importanti, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria desserts. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Fossil Cookie Pie e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 4.90,
        geological_era: "Sweet Cretaceous",
        slug: "fossil-cookie-pie",
    },
    {
        name: "Meteor Choco Sundae",
        description: "Meteor Choco Sundae e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da dessert compatto con cuore goloso e continua con cacao, crema o caramello in equilibrio. La ricetta non copia altri articoli: qui la priorita e funziona bene sia in sala sia in delivery, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria desserts. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Meteor Choco Sundae e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 5.45,
        geological_era: "Sweet Cretaceous",
        slug: "meteor-choco-sundae",
    },
    {
        name: "Amber Caramel Muffin",
        description: "Amber Caramel Muffin e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da dessert compatto con cuore goloso e continua con cacao, crema o caramello in equilibrio. La ricetta non copia altri articoli: qui la priorita e funziona bene sia in sala sia in delivery, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria desserts. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Amber Caramel Muffin e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 6.00,
        geological_era: "Sweet Cretaceous",
        slug: "amber-caramel-muffin",
    },
    {
        name: "Jurassic Brownie Bite",
        description: "Jurassic Brownie Bite e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da dessert compatto con cuore goloso e continua con cacao, crema o caramello in equilibrio. La ricetta non copia altri articoli: qui la priorita e funziona bene sia in sala sia in delivery, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria desserts. Durante le ore di punta, questa referenza viene scelta da chi cerca una firma gustativa netta e immediata. Il richiamo all era dei dinosauri rimane coerente in colore, struttura e tono aromatico. Dal punto di vista operativo, Jurassic Brownie Bite e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 6.55,
        geological_era: "Sweet Cretaceous",
        slug: "jurassic-brownie-bite",
    },
    {
        name: "Veloci Cream Cup",
        description: "Veloci Cream Cup e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da dessert compatto con cuore goloso e continua con cacao, crema o caramello in equilibrio. La ricetta non copia altri articoli: qui la priorita e funziona bene sia in sala sia in delivery, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria desserts. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Veloci Cream Cup e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 7.10,
        geological_era: "Sweet Cretaceous",
        slug: "veloci-cream-cup",
    },
    {
        name: "Predator Combo Menu",
        description: "Predator Combo Menu e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da menu costruito con logica di equilibrio porzione e continua con valore alto e percorso gustativo ordinato. La ricetta non copia altri articoli: qui la priorita e stabile in qualita durante i picchi di cassa, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria menus. Sul banco caldo, la resa rimane costante e riconoscibile dal primo all ultimo pezzo. L identita Jurassic e costruita con dettaglio, cosi ogni assaggio comunica subito appartenenza al brand. Dal punto di vista operativo, Predator Combo Menu e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 12.90,
        geological_era: "Service Era",
        slug: "predator-combo-menu",
    },
    {
        name: "Volcano Family Menu",
        description: "Volcano Family Menu e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da menu costruito con logica di equilibrio porzione e continua con valore alto e percorso gustativo ordinato. La ricetta non copia altri articoli: qui la priorita e stabile in qualita durante i picchi di cassa, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria menus. Nel flusso take away, conserva bene forma e carattere anche dopo il trasporto. Il tema preistorico non e decorativo: guida davvero il carattere del prodotto e la sua firma gustativa. Dal punto di vista operativo, Volcano Family Menu e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 13.45,
        geological_era: "Service Era",
        slug: "volcano-family-menu",
    },
    {
        name: "Explorer Lunch Menu",
        description: "Explorer Lunch Menu e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da menu costruito con logica di equilibrio porzione e continua con valore alto e percorso gustativo ordinato. La ricetta non copia altri articoli: qui la priorita e stabile in qualita durante i picchi di cassa, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria menus. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Explorer Lunch Menu e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 14.00,
        geological_era: "Service Era",
        slug: "explorer-lunch-menu",
    },
    {
        name: "Campfire Dinner Menu",
        description: "Campfire Dinner Menu e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da composizione completa con piatto principale, side e drink e continua con sequenza di consumo fluida dalla prima all ultima componente. La ricetta non copia altri articoli: qui la priorita e pensato per famiglie, gruppi e pausa lavoro, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria menus. In fascia pranzo, mantiene un ritmo alto di uscita senza perdere precisione sensoriale. L immaginario e quello delle grandi pianure mesozoiche, con un profilo aromatico ampio ma controllato. Dal punto di vista operativo, Campfire Dinner Menu e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 14.55,
        geological_era: "Service Era",
        slug: "campfire-dinner-menu",
    },
    {
        name: "Jurassic Value Menu",
        description: "Jurassic Value Menu e stato progettato come prodotto unico del nostro menu jurassico, con una personalita precisa che parte da menu costruito con logica di equilibrio porzione e continua con valore alto e percorso gustativo ordinato. La ricetta non copia altri articoli: qui la priorita e stabile in qualita durante i picchi di cassa, cosi il cliente riconosce subito una firma distinta rispetto alle altre proposte della categoria menus. Nel servizio serale, rende al massimo grazie alla stabilita della texture e alla sua costruzione intelligente. La narrazione richiama una pista di caccia nel Cretaceo: calore, terra, fumo e un finale deciso. Dal punto di vista operativo, Jurassic Value Menu e stato ottimizzato per linee fastfood reali: porzionatura coerente, montaggio rapido, tenuta in confezione e risposta gustativa stabile anche quando i volumi salgono. Il risultato finale e un prodotto con identita autonoma, pensato per restare memorabile al primo assaggio e affidabile nel tempo, senza perdere l atmosfera preistorica che definisce Jurassic Pork.",
        image: "",
        price: 15.10,
        geological_era: "Service Era",
        slug: "jurassic-value-menu",
    },
];
async function insertIntoDB(){
    for()
}
export default products;
