const burgers = [
    {
        name: "T-Rekt Burger",
        description: "Preparati per un'esperienza culinaria devastante con il nostro T-Rekt Burger! Questo capolavoro preistorico è stato creato per coloro che non temono nulla e hanno un appetito regale. Con tre generosi strati di carne di manzo 100% grass-fed, questo burger offre una potenza e una profondità di sapore che rivaleggia con il terribile T-Rex stesso. Ogni strato è sapientemente condito con spezie affumicate e pepe nero, seguito da un generoso strato di formaggio cheddar fuso che si estende come un manto di lava preistorica. I tre ingredienti principali - carne, formaggio e condimenti - rappresentano simbolicamente le tre dita terrificanti del leggendario dinosauro. La base è un panino tostato fatto in casa, morbido all'interno ma croccante fuori, perfetto per contenere questo carico di sapore esplosivo. Aggiungiamo una manciata di lattuga fresca, pomodori succosi e cipolle caramellate che aggiungono una dolcezza affascinante al profilo gustativo generale. Una generosa dose della nostra salsa BBQ affumicata fatto in casa completa questo masterpiece. Non è solo un burger, è un'esperienza che ti trasporterà direttamente nel Giurassico!",
        image: "",
        price: 14.99,
        slug: "t-rekt-burger",
    },
    {
        name: "Tricera-Chop",
        description: "Celebra il famoso Triceratopo con i suoi tre corna iconici attraverso il nostro Tricera-Chop, un burger che offre tre generose porzioni di carne di eccellenza in un unico panino magnifico! Questo burger è strutturato attorno al tema del numero tre - perfetto per chi ha tre corna... e soprattutto tre stomaci! La polpetta principale è fatta da manzo premium di primo taglio, condita con pepe nero fresco macinato, aglio, e un pizzico di timo fresco. Viene cotta perfettamente a mezzo sangue per mantenere i succhi naturali. Accanto a questa polpetta principale, abbiamo due ulteriori strati di carne che creano una vera esperienza di trinità carnivora: una striscia di pancetta affumicata croccante e una seconda polpetta più piccola di manzo wagyu che aggiunge una ricchezza supplementare. Il formaggio è un cheddar bianco invecchiato che si fonde perfettamente sotto il calore della carne. Il pane è una brioche tostata con burro e rosmarino fresco. Le verdure includono lattuga romana croccante, pomodori heirloom succosi, cipolla caramellata dolce, e un pizzico di peperoni rossi arrostiti. Una salsa speciale combina maionese, senape Dijon, e un pizzico di sriracha. Questo burger è una vera rappresentazione del concetto di tre - tre strati di carne, tre sapori principali, tre dimensioni di eccellenza!",
        image: "",
        price: 13.50,
        slug: "tricera-chop",
    },
    {
        name: "Stego-Stack",
        description: "Ispirato dalle magnifiche placche dorsali dello Stegosauro, il nostro Stego-Stack è un'architettura culinaria stratificata che sorprenderà il tuo palato con strati di carne e formaggio disposti come le placche leggendarie! Questo burger spettacolare è costruito con precisione per creare quella sensazione di scaglie sovrapposte proprio come le placche dell'antico dinosauro. La carne è una miscela di manzo wagyu e pancetta, cotta a perfetto mezzo sangue e condita con sale marino e pepe nero fresco. Il formaggio varia tra i diversi strati: cheddar invecchiato, gouda affumicato, e mozzarella di bufala si alternano creando un'esperienza gustativa sorprendente ad ogni livello. Il pane è una ciabatta tostata con rosmarino e olio d'oliva, croccante all'esterno e soffice all'interno. La vera magia sta nella salsa speciale a base di pepe smoked, un pizzico di wasabi e panna acida, che aggiunge una sensazione di piccantezza 'spinosa' perfettamente coerente con il tema. Completano il tutto lattuga croccante, pomodori heirloom, cipolle rosse in sottaceto e germogli di soia fresca. Un burger che celebra la geometria affascinante della natura preistorica con croccantezza in ogni strato!",
        image: "",
        price: 12.99,
        slug: "stego-stack",
    },
    {
        name: "Veloci-Pappataci",
        description: "Il Veloci-Pappataci è il burger perfetto per chi ha il ritmo veloce di un Velociraptor affamato e in piena caccia! Questo burger twin featuring due polpettoni di carne magra fatta da manzo alimentato a erba, garantisce una velocità di consumo impressionante mantenendo una qualità gusto eccezionale. I due burger sono composti da carne macinata finissima, condita con aglio, pepe nero, e un tocco di Worcestershire sauce per profondità incredibile. Ogni polpettone è cotto velocemente su una griglia rovente per sviluppare una crosticina affascinante all'esterno mentre rimane succoso dentro. Sono impilati su un panino brioche tostato con burro, offrendo quella dolcezza che contrasta perfettamente con la savoria della carne. Aggiungiamo formaggio cheddar fuso, crispy bacon smoked, lattuga verde fresca, pomodori succosi e la nostra segreta salsa veloce - una miscela di maionese, senape Dijon e un pizzico di sriracha. Il tutto è guarnito con cipolla fritta croccante che aggiunge una texture incredibile. Questo burger è designato per i predatori moderni!",
        image: "",
        price: 11.75,
        slug: "veloci-pappataci",
    },
    {
        name: "Bronto-Bites",
        description: "Quando la leggenda del Brontosauro, il dinosauro più grande e massiccio di tutti i tempi, incontra la cucina moderna, nasce il Bronto-Bites - un burger titanico che richiederà tutta la tua forza preistorica per essere conquistato! Questo gigante gastronomico pesa più di mezzo chilo di pura bontà carnivora ed è così enorme che sembrerà di mangiare un Brontosauro intero! Inizia con tre polpettoni enormi di manzo premium, ognuno del peso di quasi 150 grammi, cotto perfettamente a mezzo sangue per mantenere i succhi naturali incredibili. Questi giganti sono coronati da una cascata di formaggi fusi: cheddar, provolone, e una rara mozzarella di bufala che crea una sinfonia di sapori. Il pane è un pane ciabatta enorme, specialmente preparato in-house, tostato con burro e aglio per resistere al peso della creazione. Completano il tutto verdure fresche e croccanti: foglie di lattuga romana, pomodori maturi succosi, cipolle caramellate per ore, e una generosa porzione di bacon affumicato. Una salsa speciale Bronto-sauce tie tutto insieme!",
        image: "",
        price: 16.25,
        slug: "bronto-bites",
    },
    {
        name: "Raptor-Rip",
        description: "Preparati per un'esperienza selvaggia e adrenalinica con il nostro Raptor-Rip, un burger che non ha pietà e che strapperà letteralmente i tuoi sensi nel vortice del piacere gastronomico! Questo burger feroce è costruito attorno a una polpetta di manzo affumicato speziato con peperoncino habanero, pepe nero, e un pizzico di cayenna che crea una sensazione di fuoco graduale e controllato nel palato. La carne è cotta in modo da sviluppare una crosticina affascinante mentre l'interno rimane succoso e saporito. Su questo letto di carne feroce poniamo formaggio pepper-jack che aggiunge una piccantezza secondaria affascinante. Il vero protagonista dell'esperienza 'Raptor' sono gli 'artigli' - strisce croccantissime di cipolla fritta in una pastella speciale, condite con paprika affumicata e pepe nero. Queste cipolle 'artiglianti' creano una texture incredibile e aggiungono un'ulteriore dimensione croccante. Il pane è un focaccia nero fatto con farina integrale e semi di sesamo nero, tostato per esaltare la sua robustezza. Una salsa killer ti lascerà senza fiato!",
        image: "",
        price: 12.50,
        slug: "raptor-rip",
    },
    {
        name: "Pachy-Pound",
        description: "Ispirato dalla testa massiccia e robusta del Pachicefalosauro, il nostro Pachy-Pound è un burger che colpisce forte con ogni morso che prendi! Questo burger è costruito su una base di carne di manzo premium, macinata finissima e compattata in una polpetta densa e potente che mantiene la sua integrità strutturale sotto il peso dei toppings. La carne è stagionata con una miscela di spezie robuste: pepe nero macinato, aglio, sale marino e un pizzico di smoked paprika. Viene cotta su una griglia bollente per creare una crosta caramellizzata sulla superficie, sigillando i succhi naturali all'interno. Su questo fondamento robusto poniamo ben due strati di formaggio cheddar invecchiato, che si fonde creando un'aderenza incredibile. Il pane è un pane di segale scuro, tostato e condito con burro affumicato, robusto abbastanza da sostenere il peso del burger senza sgretolarsi. Aggiungiamo bacon croccante affumicato, lattuga romana, pomodori maturi, e cipolle rosse in sottaceto per aggiungere acidità e croccantezza. Colpo dopo colpo di sapore incredibile!",
        image: "",
        price: 13.99,
        slug: "pachy-pound",
    },
    {
        name: "Ankylo-Armour",
        description: "Come l'Ankilosauro era protetto da una corazza di armature naturali, il nostro Ankylo-Armour è blindato da uno scudo incredibile di formaggi grigliati che protegge una delizia interna di carne perfettamente cotta! Questo burger unico è racchiuso completamente da un guscio esterno di formaggi misti grigliati: una combinazione di cheddar, mozzarella e provolone affumicato, tutti fusi insieme e cotti su una griglia fino a creare una crosta dorata e croccante che è praticamente impenetrabile. Sotto questo scudo di formaggio si cela una polpetta di manzo wagyu, cotta a perfetto mezzo sangue con una bella crosticina caramellizzata. La carne è condita con aglio, timo fresco, e un pizzico di pepe nero. Il pane interno è un brioche morbido e burroso, perfetto per contenere i succhi della carne senza dissolversi. Aggiungiamo lattuga fresca, pomodori succosi, cipolle caramellate, e una salsa speciale. Niente può penetrare questo bunker di sapore!",
        image: "",
        price: 13.25,
        slug: "ankylo-armour",
    },
    {
        name: "Iguano-Don't",
        description: "Non saltare questo capolavoro culinario! L'Iguano-Don't è il burger perfetto per chi cerca un'esperienza audace, fresca e completamente preistorica senza compromessi sulla qualità del sapore. Questo burger è costruito attorno a una polpetta di manzo magro alimentato a erba, condita con erbe fresche come basilico, prezzemolo e origano fresco - un tributo al fatto che l'Iguanodonte si nutriva di vegetazione fresca e varia. La carne è cotta a mezzo sangue e ha una texture incredibilmente succosa e saporita in ogni morso. Su questa base di carne poniamo un formaggio fresco di capra che aggiunge una tannicità affascinante e contrasta meravigliosamente con la ricchezza della carne. Il pane è un pane integrale fatto con farina di quinoa, ricco di sapore e texture, tostato leggermente con olio d'oliva. Aggiungiamo verdure croccanti e fresche: rucola pepata, pomodori heirloom, cetrioli sottili, e una manciata di germogli di luzerna che aggiungono una freschezza cruda assoluta.",
        image: "",
        price: 10.99,
        slug: "iguano-dont",
    },
    {
        name: "Carno-Carnival",
        description: "Festeggia come un vero Carnosauro con il nostro Carno-Carnival - un burger che incarna la gioia pura di mangiare carne eccezionale e tanto, tanto divertimento gastronomico! Questo burger celebrativo è un vero spettacolo carnivoro con quattro tipi diversi di carne in armonia perfetta: polpetta di manzo premium, guancia di manzo cotta a bassa temperatura, pancetta affumicata croccante, e un tocco di spalla di maiale per aggiungere una dolcezza sottile. Ogni tipo di carne contribuisce una texture e un sapore unico, creando un'esperienza multi-sfaccettata in ogni morso incredibile. Il formaggio è una miscela di smoked gouda e cheddar bianco affinato, che si fonde creando una base cremosa per tutte le carni. Il pane è un pane alla birra con aglio, fatto in-house e tostato con burro e erbe aromatiche fino a diventare dorato e incredibilmente fragrante. Per aggiungere al 'Carnival' dell'esperienza, aggiungiamo cipolle caramellate croccanti, lattuga verde croccante, pomodori succulenti!",
        image: "",
        price: 14.50,
        slug: "carno-carnival",
    },
    {
        name: "Deinony-Down",
        description: "Scendi profondamente negli abissi del Cretaceo con il nostro Deinony-Down, un burger che ti porterà in un viaggio verticale verso il centro della ricchezza gustativa e della soddisfazione culinaria! Questo burger è costruito su strati affascinanti che vanno verso il basso, proprio come si scende nel tempo geologico. La polpetta di manzo è cotta lentamente con affumicatura a freddo utilizzando legno di hickory, che impregnala carne con un sapore affumicato profondo e complesso. La carne è condita con pepe nero fresco macinato, aglio, e un pizzico di cayenna che crea una sensazione piccante delicata. Il formaggio smoked gouda aggiunge un'ulteriore profondità di fumo che completa meravigliosamente la polpetta. Il pane è un pane di segale scuro con semi di cumino, che aggiunge una nota aromatica affascinante a tutto il burger. Su questo fondamento affumicato poniamo verdure che aggiungono freschezza: lattuga iceberg croccante, pomodori maturi, e cipolla rossa sottile.",
        image: "",
        price: 12.75,
        slug: "deinony-down",
    },
    {
        name: "Ptera-Pack",
        description: "Preparati a volare alto nel cielo della felicità gastronomica con il nostro Ptera-Pack, il burger ideale per chi vuole leggerezza senza sacrificare la qualità e il sapore incredibile! Nonostante il tema del Pterodattilo suggerisca leggerezza assoluta, questo burger è denso di sapore e sorprese piacevoli. La polpetta è fatta da una miscela leggera di pollo alimentato a erba e manzo magro, che mantiene la succulentezza della carne rossa mentre offre una texture leggermente più leggera. La carne è condita con erbe fresche: timo, rosmarino e un pizzico di zenzero che aggiunge una nota fresca e vivace. Il formaggio è una mozzarella di bufala leggera e cremosa che si fonde dolcemente. Il pane è speciale: un pane bianco leggero fatto con soia e farina d'avena, che offre una base substantiva senza essere pesante. Aggiungiamo verdure croccanti e fresche: rucola, pomodori heirloom, cipolla rossa sottile, e cetrioli.",
        image: "",
        price: 11.25,
        slug: "ptera-pack",
    },
    {
        name: "Sauro-Supreme",
        description: "Questo è il supremo dei supremi - il Sauro-Supreme è il nostro capolavoro reale, riservato solo ai veri intenditori di burger di classe mondiale e sapore straordinario! Questo burger incarna la nobiltà, l'eleganza e l'eccellenza in ogni aspetto. La polpetta è fatta da manzo wagyu importato, una delle carni più pregiate e marmorizzate del mondo, garantendo una succulentezza e una ricchezza di sapore incomparabili. La carne è cotta perfettamente a mezzo sangue su una piastra di ferro scaldato a 400 gradi, creando una crosta caramellizzata straordinaria. Il formaggio non è uno, ma tre: Comté invecchiato, truffle pecorino, e una rara robiola di Lombardia, ognuno fornendo un profilo gustativo nobile e complesso. Il pane è un pane fatto in-house con farina di spelta biologica e burro alimentato a erba, tostato perfettamente e condito con olio di truffle.",
        image: "",
        price: 15.75,
        slug: "sauro-supreme",
    },
    {
        name: "Fossil-Feast",
        description: "Scopri i sapori preservati da milioni di anni con il nostro Fossil-Feast, un burger fossile-mente delizioso che celebra la conservazione dei gusti più autentici e antichi della cucina preistorica! Questo burger ricorda come i fossili conservano la storia, così questo burger conserva i sapori tradizionali e i metodi di cottura ancestrali che hanno trionfato attraverso l'epoca. La polpetta è fatta da manzo che viene stagionato per 30 giorni in una camera a freddo, permettendo ai sapori naturali di concentrarsi e intensificarsi come un fossile nel tempo. La carne è cotta utilizzando la tecnica più antica: direttamente su carboni caldi senza grasso aggiunto, permettendo ai sapori naturali di brillare magnificamente. Il formaggio è un cheddar invecchiato 3 anni, che ha sviluppato cristalli di complessità e profondità incredibile. Il pane è fatto con lievito madre vivo da 50 anni, che aggiunge una complessità fermentata incredibile.",
        image: "",
        price: 13.00,
        slug: "fossil-feast",
    },
    {
        name: "Meteor-Melt",
        description: "Immagina un asteroide di formaggio che cade dal cielo e si schianta dritto sopra il tuo burger - questo è il Meteor-Melt! Un burger spettacolare dove il formaggio letteralmente fuso (come fosse colpito dall'impatto del meteorite) si riversa sulla carne sottostante creando una vera esplosione di sapore incrediible. La polpetta di manzo è una miscela di spalla e costolette, cotta su una griglia rovente fino a diventare incredibilmente succosa. Sopra questa base di carne viene versato direttamente del formaggio fuso - una miscela di cheddar fuso, emmental, e gouda affumicato - che è stato scalandato e versato come lava incandescente di formaggio puro. L'effetto è visivo e delizioso, con il formaggio che cade dai lati della polpetta e si raffredda mentre continua a gocciolare. Il pane è un brioche extra tostato e burroso, designato per contenere il flusso di formaggio fuso senza disintegrarsi. Effetto asteroide garantito!",
        image: "",
        price: 14.25,
        slug: "meteor-melt",
    },
    {
        name: "Dino-Dynamo",
        description: "Sentirai l'energia dinamica di un dinosauro in piena caccia con ogni morso del nostro Dino-Dynamo, un burger che è letteralmente esplosione di energia e sapore incredibile! Questo burger è creato appositamente per fornire l'energia necessaria per affrontare la giornata con la forza di un predatore preistorico. La polpetta è fatta da una miscela energetica di manzo magro, con proteina aggiunta da germe di grano e semi di zucca tostati, che fornisce una spinta nutrizionale al di là della carne pura. È condita con aglio, pepe nero, e un pizzico di curcuma per aggiungere proprietà anti-infiammatorie e energetiche. Il formaggio è mozzarella fresca per mantenerlo leggero ma saporito. Il pane è fatto con farina integrale, semi di lino, e chia - designato per fornire energia sostenuta. Aggiungiamo verdure energetiche: spinaci crudi per ferro, pomodori per licopene, e germogli di broccoli per sulforafano.",
        image: "",
        price: 12.99,
        slug: "dino-dynamo",
    },
    {
        name: "Cretaco-Crunch",
        description: "Preparati per un'esperienza croccante che ricorda le rocce mineralizzate del periodo Cretaceo! Il Cretaco-Crunch è tutto incentrato sulla texture - croccantezza da ogni angolo, ogni morso, ogni strato del burger magnifico. La polpetta di manzo è cotta con tecniche speciali per sviluppare una crosticina esterna incredibilmente croccante mentre la parte interna rimane succosa. Sopra la polpetta poniamo bacon affumicato tostato fino a diventare ultra-croccante, quasi vetroso nella sua fragilità. Il pane è tostato fino al punto di essere quasi scricchiolante - non bruciato, ma con quella tostatura perfetta che crea una crosta audibile. La vera magia della croccantezza viene dalle nostri 'rocce del Cretaceo' - cipolle fritte appositamente preparate: fette sottili di cipolla tuffate in una pastella leggera con amido di mais, fritte in olio a 180 gradi fino a diventare dorate, croccanti e praticamente caramellizzate.",
        image: "",
        price: 13.50,
        slug: "cretaco-crunch",
    },
    {
        name: "Saurus-Sauce",
        description: "Il vero segreto di questo burger è la leggendaria salsa Saurus-Sauce, una ricetta misterica che è stata tramandata attraverso i secoli del Mesozoico e che noi abbiamo finalmente riportato in vita! Questa salsa è il vero protagonista del burger, con ogni altro ingrediente giocando un ruolo di supporto fondamentale. La polpetta è una semplice miscela di manzo magro, cotta al mezzo sangue e condita minimamente con solo sale e pepe, permettendo alla salsa di brillare perfettamente. Il formaggio è un semplice cheddar bianco, che non compete con i sapori della salsa. Il pane è semplice brioche, senza tostatura eccessiva, pronto a ricevere la gloria della salsa misteriosa. Ora, la salsa Saurus-Sauce è un mistero sapido di ingredienti: inizia con una base di maionese fatta in casa, a cui vengono aggiunti i seguenti ingredienti segreti (o almeno, loro credono siano segreti): un pizzico di estratto di mandorla, aceto balsamico di 15 anni!",
        image: "",
        price: 11.99,
        slug: "saurus-sauce",
    },
    {
        name: "Terrore-Tri",
        description: "La trinità del terrore e della delizia gastronomica si riunisce nel nostro Terrore-Tri, un burger che presenta tre distinte espressioni di eccellenza carnivora in armonia perfetta! Primo elemento della trinità: una polpetta di manzo wagyu premium con una crosticina caramellizzata che crackle quando la mordi. Secondo elemento: un'affettata di guancia di manzo cotta lentamente per 12 ore a bassa temperatura, che è diventata incredibilmente tenera e ricca di collagene naturale che si trasforma in gelatina succosa. Terzo elemento: una striscia di bacon di pancetta francese, affumicato e cotto fino a una fragilità croccante. Queste tre forme di eccellenza carnivora sono stratificate sul pane brioche tostato con burro. Il formaggio è una trinità anch'esso: cheddar invecchiato, smoked gouda, e brie fresco - tre formaggi che rappresentano tre epoche e tre sapori diversi. Le verdure sono selezionate per complementare senza dominare!",
        image: "",
        price: 14.75,
        slug: "terrore-tri",
    },
    {
        name: "Giga-Gobble",
        description: "Se il Gigantosauro, il mostro supremo del Cretaceo, avesse un nome per questo burger sarebbe il Giga-Gobble - una creazione così massiccia, così potente, così travolgentemente carnivora che richiede il coraggio di un vero predatore top per affrontarla! Questo burger è una dichiarazione di intenti puri: pura carne in tutte le sue forme gloriose. La polpetta è un colosso di 250 grammi, fatto da una miscela di manzo primo taglio, cotto su una piastra rovente fino a sviluppare una crosticina caramellizzata incredibile. Ma non è solo una polpetta - è accompagnata da uno strato di pancetta affumicata, uno strato di salsiccia italiana piccante, uno strato di spalla di manzo cotta a bassa temperatura, e infine uno strato di fegato di vitello grigliato. Quattro formaggi diversi fondono sotto il calore della carne: cheddar bianco invecchiato, provolone affumicato, fontina italiana, e un formaggio blu dolce!",
        image: "",
        price: 16.99,
        slug: "giga-gobble",
    },
    {
        name: "Spinosaur-Spinner",
        description: "Il Spinosauro, con le sue spine dorsali iconiche, ispira il nostro Spinosaur-Spinner, un burger che è stato letteralmente fatto girare sulla griglia per sviluppare una superficie spinosa di sapore affumicato e piccantezza! La polpetta di manzo viene cotta utilizzando una tecnica speciale: viene girata costantemente (ogni 30 secondi) sulla piastra rovente per creare una crosticina segmentata e increspata che ricorda le spine del dinosauro. Questo movimento costante sviluppa una crosticina incredibile attraverso la reazione di Maillard accelerata. La carne è condita liberalmente con pepe nero fresco macinato, non solo sale - questo è il vero ingrediente 'spina' del burger. Il pepe nero pizzica delicatamente il palato senza sopraffare, creando quella sensazione di 'spine' del gusto. Il formaggio è pepper-jack, che aggiunge un ulteriore strato di pizzicantezza calda e affascinante. Il pane è tostato con olio d'oliva e semi di sesamo nero, che aggiungono un elemento croccante e terroso perfetto.",
        image: "",
        price: 13.75,
        slug: "spinosaur-spinner",
    },
    {
        name: "Compy-Combo",
        description: "Non lasciarti ingannare dalle dimensioni! Il Compy-Combo è piccolo solo in apparenza come il Compsognathus, ma pacchetto dentro un'esplosione di sapori micidiali e ben coordinati! Questo burger abbraccia il concetto di piccolo ma potente. La polpetta è piccola e compatta (100 grammi), ma è fatta da una miscela meticolosamente selezionata di manzo Premium grass-fed, con aggiunta di un grattuggiamento di mandorla appena tostata per aggiungere texture croccante e sapore di nocciola sottile. Viene cotta perfettamente al mezzo sangue e sviluppa una crosticina dorata incredibile. Il formaggio è un pezzo singolo di emmental invecchiato, che aggiunge complessità svizzera. Il pane è un mini panino ciabatta, fatto con impasto di lunga fermentazione, tostato leggermente. Quello che rende questo burger 'micidiale' è la combinazione di condimenti piccoli ma potenti: un pizzico di mostarda Dijon, un paio di acciughe non riconoscibili che aggiungono umami profondo!",
        image: "",
        price: 10.50,
        slug: "compy-combo",
    },
    {
        name: "Spikey-Special",
        description: "Uno special condito generosamente con peperoncini che hanno punte affilate come le spine di un dinosauro! Questo burger celebra la piccantezza stratificata e le sorprese fiammeggianti. La polpetta di manzo è una miscela saporita condita con aglio, pepe nero, e un pizzico di paprika affumicata. Viene cotta perfettamente. Il formaggio è pepper-jack che aggiunge calore intrinseco. Il pane è tostato leggermente con olio d'oliva piccante. Le verdure sono tutte piccanti per eccellenza: jalapeños freschi affettati sottilmente con i loro semi intatti per massimo fuoco, peperoni rossi piccanti arrostiti, rucola selvatica pepata, cipolla rossa in sottaceto piccante. Una salsa speciale 'Spinosa' fatta da sriracha piccante, panna acida, limone fresco, e un pizzico di peperoncino fantasma schiacciato crea un fuoco che costruisce gradualmente. Il tutto è guarnito con semi di sesamo nero e un pizzico di polvere di pepe cayenna. Questo burger è una celebrazione delle spine, del fuoco, e della piccantezza straordinaria - ogni morso rilascia un'onda di calore affascinante!",
        image: "",
        price: 12.25,
        slug: "spikey-special",
    },
    {
        name: "Jurassic-Jackpot",
        description: "Hai vinto il jackpot gastronomico! Il Jurassic-Jackpot è la riunione di tutti gli ingredienti più premium, più rari, più straordinari che abbiamo potuto raccogliere dal nostro arsenale culinario preistorico! Questo burger è il nostro manifesto di eccellenza, dove non si fa compromessi su nulla. La polpetta è un'orchestra di eccellenza: manzo wagyu giapponese A5, manzo Hereford britannico, e aggiunta di un pizzico di manzo Angus scozzese, il tutto mescolato per creare un profilo di sapore stratificato e complesso. Viene cotta perfettamente. Il formaggio è un trio reale: comté francese di 36 mesi invecchiato, manchego spagnolo invecchiato, e una rara formaggio di latte crudo di monte alpino. Le verdure sono tutte selezionate da piccoli coltivatori biologici: lattuga rossa di Treviso, pomodori neri di Crimea, cipolla dolce di Tropea, e arugula di montagna. Il bacon è un pancetta di suino di Parma invecchiato, affumicato ed essicato naturalmente. Il pane è fatto con una miscela di farine rare: farina bianca di grano antico Kamut, farina integrale di spelta, e un pizzico di farina di farro. Una salsa finale 'Jackpot' combina riduzione di truffle nero, panna acida di capra, riduzione balsamica di 50 anni, e un pizzico finale di sale Maldon. Questo burger non è solo cibo - è la vittoria della qualità!",
        image: "",
        price: 15.50,
        slug: "jurassic-jackpot",
    },
    {
        name: "Dilophosauro-Double",
        description: "Due teste intelligenti sono meglio di una, e così due polpette sono definitivamente meglio di una! Il Dilophosauro-Double celebra il dinosauro con due creste testa con due straordinarie polpette di carne impilate una sopra l'altra, creando una vera esperienza di doppio strato! La polpetta inferiore è fatta da manzo della guancia, cotta lentamente fino a diventare incredibilmente tenera e ricca di collagene che si trasforma in succulenza naturale. La polpetta superiore è fatta da una miscela di manzo primo taglio e pancetta, creando un profilo più croccante e ricco. Una sottile strato di formaggio smoked gouda le separa, aggiungendo una barriera sapida. Le due polpette insieme creano un'altezza impressionante - letteralmente due teste di dinosauro impilate verticalmente! Il pane è un focaccia grossa, tostato in maniera che possa supportare il peso e la complessità della doppia polpetta. Le verdure sono aggiunte tra le due polpette (crisps di cipolla caramellata) e attorno al pane (lattuga fresca, pomodori, peperoni arrostiti). Una salsa barbecue affumicata tiene tutto insieme. La vera magia è il contrasto incredibile tra la dolcezza della guancia inferiore e la ricchezza della pancetta superiore!",
        image: "",
        price: 14.00,
        slug: "dilophosauro-double",
    },
    {
        name: "Ostrich-Osaur",
        description: "Non confondere questo burger leggero e veloce con uno struzzolo ordinario - il nostro Ostrich-Osaur è pura dinamite preistorica in forma compatta e snella! La polpetta è fatta da carne di struzzo fresco, una carne rossa magra incredibilmente saporita che è molto più magra del pollo e ha un profilo proteico superiore. La carne di struzzo è cotta velocemente su una piastra rovente per sviluppare una crosticina dorata senza asciugarla internamente. Il formaggio è un pecorino romano giovane, che aggiunge un poco di salmastro e complessità. Il pane è un mini panino integrale, leggero ma sostanziale, tostato leggermente. Quello che rende questo burger 'dinamite' è la combinazione di velocità e potenza: le verdure sono minime ma potenti - un pizzico di rucola pepata, uno spicchio di aglio affettato sottile, un pizzico di pepe nero fresco, pomodori succosi, e un drizzle finale di olio d'oliva piccante. Una salsa piccante ma leggera fatta da maionese con un pizzico di pepe rosso completa il quadro. Veloce come lo struzzo, saporito come un dinosauro!",
        image: "",
        price: 11.50,
        slug: "ostrich-osaur",
    },
    {
        name: "Theri-Thrill",
        description: "Il Terizinosauro, con le sue artigli giganti lunghe come spade, ispira il nostro Theri-Thrill, un burger dove gli 'artigli' di formaggio grattato sono l'elemento centrale che crea quella particolare sensazione di brivido! La polpetta di manzo è cotta perfettamente, ma il vero protagonista sono gli 'artigli' - lunghe strisce di formaggio parmigiano-reggiano grattugiato finemente e cotto leggermente sulla piastra calda fino a diventare secco e croccante. Questi artigli di formaggio vengono posizionati intorno alla polpetta in maniera che sporgono drammaticamente dalle spalle del panino, creando un effetto visivo di un dinosauro che ti minaccia con le sue artigli! La polpetta sottostante è una miscela di manzo e pancetta, condita con aglio e timo. Il formaggio è una base di mozzarella fusa sotto il calore della polpetta. Il pane è una focaccia tostata leggera con olio d'oliva. Le verdure sono minime - un pizzico di lattuga fresca, pomodori maturi, cipolla rossa - permettendo agli 'artigli' di formaggio di dominare. Una salsa italiana fatta da maionese con basilico fresco, limone e aglio completa il profilo!",
        image: "",
        price: 13.99,
        slug: "theri-thrill",
    },
    {
        name: "Allo-Alloy",
        description: "L'Allosaurus era conosciuto come il 'leone del Giurassico' - brutale, puro e totalmente affascinante - esattamente come la nostra 'lega' di sapori nel nostro Allo-Alloy! Questo burger è una composizione metallurgica di eccellenza dove ogni elemento è scelto per la sua brutalità pura e il suo fascino primitivo. La polpetta è una miscela: 70% manzo di bisonte (per brutalità primitiva), 20% manzo wagyu (per ricchezza), 10% pancetta di anatra (per complessità affumicata). Viene cotta su una piastra molto calda fino a sviluppare una crosticina incredibilmente croccante e caramellizzata. Il formaggio è una miscela di cheddar invecchiato e formaggio blu dolce - la combinazione di dolcezza e piccantezza crea un contrasto affascinante. Il pane è nero, fatto con carbone vegetale e segale, conferendo un aspetto primitivo e brutale. Le verdure sono forti e non apologetiche: cipolla rossa cruda affettata sottile, peperoni rossi arrostiti, rucola selvatica pepata. Una salsa 'Allo' speciale fatta da maionese scura con aceto nero, pasta di pepe, e un pizzico di salsa di soia aggiunge profondità umami!",
        image: "",
        price: 12.50,
        slug: "allo-alloy",
    },
    {
        name: "Europ-Eater",
        description: "L'Europasaurus era il terribile dinosauro che mangiava con un appetito insaziabile, e il nostro Europ-Eater incarna quella stessa fame vorace di condimenti, sapori e esperienze! Questo burger non è timido - è coraggioso nella sua dichiarazione di volere tutto. La polpetta di manzo è una miscela interessante di spalla e costolette, cotta al mezzo sangue e condita con erbe fresche: rosmarino, timo, e origano. Il formaggio è un trio: cheddar bianco, mozzarella fresca, e un piccolo pezzetto di brie per aggiungere cremosità. Il vero punto focale è la 'fame' del burger per i condimenti - questo burger viene caricato generosamente con strati multipli di verdure e condimenti: doppio strato di cipolla caramellata, insalata mista di rucola e lattuga, pomodori heirloom affettati grossi, peperoni rossi e gialli arrostiti, sottaceti croccanti, germogli di brocoli freschi. Una salsa speciale 'Affamato' fatta da una miscela di BBQ sauce, sriracha, e panna acida completa il profilo straordinario!",
        image: "",
        price: 11.75,
        slug: "europ-eater",
    },
    {
        name: "Mamenchis-Munch",
        description: "Potrebbe sembrare che il Mamenchis-Munch dovrebbe essere vegetariano, dato che il Mamenchisaurus era un erbivoro gigante che si nutriva di foglie e vegetazione, ma no! Questo burger è umoristicamente nominato per celebrare l'ironia di un burger 'da erbivoro' che è invece 100% carnivoro puro! La polpetta di manzo è una miscela geniale di carne rossa, pancetta affumicata, e un pizzico di carne d'anatra per aggiungere complessità. Viene cotta perfettamente fino a mezzo sangue. Il formaggio è un semplice ma elegante cheddar invecchiato. Il pane è un pane integrale robusto con semi di girasole, che crea un contrasto ironico con il contenuto puramente carnivoro. Ma ecco l'ironia vera - le verdure! Nonostante il burger sia principalmente carnivoro, lo carichiamo di verdure come un erbivoro: lattuga, rucola, pomodori, cetrioli, germogli, carote affettate sottile. Poi aggiungiamo bacon croccante, pancetta di anatra fritta, e guancia di manzo cotta lentamente!",
        image: "",
        price: 10.99,
        slug: "mamenchis-munch",
    },
    {
        name: "Mosasaur-Master",
        description: "Il Mosasauro era il re dei mari preistorici, e il nostro Mosasaur-Master porta i sapori oceanici in terra ferma con grazia e umidità pura! Questo burger ha un'umidità caratteristica che ricorda l'ambiente oceanico da cui il Mosasauro regna. La polpetta è una miscela affascinante: 60% manzo, 40% pesce (salmone selvatico del Pacifico) - creando un ponte tra terra e mare. La carne è cotta velocemente per mantenere l'umidità inherente. Il formaggio è un formaggio di capra fresco che aggiunge una cremosità e umidità addizionale. Il pane è un brioche al burro extra burroso, tostato leggermente per creare una base che può assorbire l'umidità. L'elemento chiave dell'umidità viene dalle condimenti: le verdure vengono preparate in una marinata leggera di aceto bianco, olio d'oliva, e erbe - lattuga marina, pomodori marinati, cipolla rossa in aceto, cetriolo in salamoia leggera!",
        image: "",
        price: 14.99,
        slug: "mosasaur-master",
    },
    {
        name: "Quetzal-Quest",
        description: "Intraprendi una quest verso il cielo con il nostro Quetzal-Quest, un burger imponente, colorato e maestoso come il Quetzalcoatlus, il più grande pterosauro mai volato! Questo burger è costruito verticalmente - una vera impresa architettonica che richiede varie spinte verso l'alto. La polpetta di manzo è cotta su una piastra rovente per sviluppare una crosticina incredibile e mantiene i succhi vitali all'interno. Il formaggio è un cheddar giallo brillante che aggiunge un elemento di colore dorato. Il pane è un pane integrale alla curcuma tostato con burro chiarificato - il colore giallo aggiunge al tema colorato. Quello che rende questo burger veramente una 'quest' verso il cielo è l'architettura stratificata: ogni strato aggiunge un colore diverso - rosso, giallo, verde, viola - creando un effetto arcobaleno!",
        image: "",
        price: 15.25,
        slug: "quetzal-quest",
    },
    {
        name: "Trilobite-Treat",
        description: "Un'antica prelibatezza fossile dal fondo dei mari preistorici - il Trilobite-Treat! Ok, sì, è 'solo' un burger, ma che burger! Nonostante il Trilobite sia un invertebrato marino e non esattamente una fonte proteica, il nostro Trilobite-Treat è un omaggio ai fossili più iconici della preistoria con un burger che incorpora ingredienti 'fossili' - ingredienti che sembrano usciti direttamente dal passato primitivo! La polpetta è una miscela di carni scure: un poco di manzo, un poco di cinghiale, un poco di lepre selvatica - sapori primitivi e forti che ricordano le carni cacciate nel Paleozoico. La carne è cotta su carboni caldi per massimizzare il sapore affumicato primitivo. Il formaggio è un vecchio cheddar molto invecchiato, quasi croccante per la cristallizzazione naturale. Il pane è fatto con un lievito madre di 100 anni, conferendo uno stato di quasi 'fossilizzazione'!",
        image: "",
        price: 9.99,
        slug: "trilobite-treat",
    },
    {
        name: "Ichthy-Infinite",
        description: "Infinitamente delizioso! L'Ittiosauro nuota infinitamente nei mari giurassici, e il nostro Ichthy-Infinite ti offre un'esperienza infinita di freschezza, sapore, e oceano! Questo burger celebra la natura infinita della nuotata marina e del sapore del pesce. La polpetta è principalmente pesce - salmone rosso selvaggio del Pacifico, ma con un tocco di manzo magro (30%) per aggiungere struttura e umami. Il pesce è arrostito delicatamente sulla piastra per mantenere la tenerezza. Il formaggio è una mozzarella di bufala fresca, leggera e cremosa come l'acqua marina. Il pane è un pane bianco ariostato fatto con farina di grano senatore Cappelli, molto leggero e soffice. Le verdure sono tutte fresche e oceaniche: rucola selvatica marina, pomodori freschi succosi, cetrioli dolci croccanti, germogli di alfa-alfa fresco, e foglie di lattuga dolce da serra!",
        image: "",
        price: 12.00,
        slug: "ichthy-infinite",
    },
    {
        name: "Pterano-Party",
        description: "Una festa di sapori che vola alto nel cielo! Se il Pteranodon facesse una festa, questo burger sarebbe il piatto d'onore, il pezzo centrale, la celebrazione assoluta di tutte le cose buone! Questo burger è una festa di trama, colore, e sapore. La polpetta è una miscela di manzo premium e pancetta di maiale, cotta a mezzo sangue per mantenere la succosità. Il formaggio è un cheddar giallo brillante che aggiunge al tema festivo. Il pane è una brioche con semi di sesamo bianco e nero, che ricorda i disegni delle ali del Pteranodon. La vera festa inizia con i condimenti - questo burger viene caricato generosamente: due strati di cipolla caramellata, lattuga croccante, pomodori heirloom affettati generosamente, peperoni rossi e gialli arrostiti, bacon croccante affumicato!",
        image: "",
        price: 13.50,
        slug: "pterano-party",
    },
    {
        name: "Coelo-Cool",
        description: "Fresco come il Celofisi nelle fredde notti preistoriche, il Coelo-Cool è un burger minimalista ma straordinario che celebra la semplicità elegante e la freschezza pura! Questo burger rifiuta deliberatamente l'eccesso - non è caricato di ingredienti, ma invece celebra la qualità assoluta di ogni singolo elemento scelto. La polpetta di manzo è una miscela semplice di manzo grass-fed primo taglio, stagionata per 30 giorni, condita solo con sale marino e pepe nero fresco - nient'altro. Viene cotta su una piastra molto calda fino a sviluppare una crosticina incredibile. Il formaggio è un pezzo singolo di emmental svizzero invecchiato, che aggiunge dolcezza naturale. Il pane è un mini panino di pane bianco classico, tostato leggermente con burro. Le verdure sono minime ma perfette: una singola foglia di lattuga verde dolce, uno spicchio di pomodoro rosso maturo, una sottile fetta di cipolla dolce!",
        image: "",
        price: 10.75,
        slug: "coelo-cool",
    },
    {
        name: "Corytho-Craze",
        description: "Una follia totale di sapori con una corona di formaggio in cima, proprio come il crest distintivo del Corythosaurus! Il Corytho-Craze è un burger che non teme l'eccesso e celebra la pazzia sensoriale in ogni forma. La polpetta di manzo è una miscela ricca di gusto - manzo premier, pancetta affumicata, e un pizzico di spalla di manzo cotta a bassa temperatura per aggiungere complessità e tenerezza. Viene cotta perfettamente al mezzo sangue. Il pane è una brioche extra burrosa che può sopportare il peso dell'eccesso. La vera 'corona' di questo burger è una struttura di formaggio fuso caldo posizionata verticalmente sopra la polpetta - una miscela di cheddar, provolone, e mozzarella fusa insieme in una forma che ricorda il crest distintivo del Corythosaurus. Il resto del burger è caricato generosamente: doppio strato di cipolla caramellata, bacon croccante affumicato!",
        image: "",
        price: 13.25,
        slug: "corytho-craze",
    },
    {
        name: "Thescelosaurus-Tasty",
        description: "Piccolo ma incrediblimente delizioso! Il Thescelosaurus era un piccolo dinosauro intelligente che rappresentava un'eccellenza in forma compatta, e il nostro Thescelosaurus-Tasty celebra perfettamente questa idea. Questo burger è perfetto per coloro che vogliono qualcosa di più leggero ma non vogliono compromessi sulla qualità. La polpetta è di soli 80 grammi - una quantità intenzionalmente piccola ma fatta dalla miscela più pregiata possibile: 50% manzo wagyu A5 giapponese, 30% bisonte americano, 20% pancetta affumicata. Ogni grammo è pura eccellenza. Viene cotta perfettamente su una piastra rovente. Il formaggio è un piccolo pezzo di comté francese invecchiato 36 mesi. Il pane è un mini panino di segale scura fatto con impasto di lunga fermentazione. Le verdure sono minime ma perfette: una singola foglia di rucola selvatica, uno spicchio di pomodoro heirloom nero!",
        image: "",
        price: 9.50,
        slug: "thescelosaurus-tasty",
    },
    {
        name: "Maiasaura-Magic",
        description: "La magia della madre dinosauro si manifesta in ogni boccone del nostro Maiasaura-Magic - un burger nutrente, potente e che nutre come solo una madre potrebbe! Il Maiasaura era conosciuta per la sua dedizione materna straordinaria, e questo burger incarna quell'amore attraverso ingredienti nutrienti e sazianti. La polpetta è una miscela intelligente di manzo nutriente, aggiunta di semi di zucca tostati (per ferro e minerali) e noci sminuzzate (per grassi sani). La carne è cotta perfettamente. Il formaggio è un formaggio di capra ricco di probiotici benefici. Il pane è fatto con farina integrale biologica, semi di lino, chia, e un poco di miele naturale - un pane che nutre veramente. Le verdure sono tutte scelte per il valore nutrizionale: spinaci crudi ricchi di ferro, pomodori rossi ricchi di licopene, cipolla rossa ricca di antiossidanti!",
        image: "",
        price: 12.75,
        slug: "maiasaura-magic",
    },
    {
        name: "Leptoceratops-Lite",
        description: "Un burger leggero ma straordinariamente resistente e pieno di sapore, proprio come il Leptoceratops - il piccolo dinosauro che miracolosamente sopravvisse alla fine del Cretaceo! Questo burger celebra l'idea che talvolta i più piccoli e leggeri sono i veri sopravvissuti. La polpetta è leggera ma resistente: una miscela di pollo bianco magro (70%) e manzo magro (30%), che crea una base di proteine magra e duratura. La carne è cotta perfettamente senza perdere i succhi naturali. Il formaggio è un pecorino fresco leggero, non grasso ma ricco di sapore. Il pane è fatto con farina di grano saraceno - una farina antica e resiliente, tostato leggermente. Le verdure sono tutte leggere ma robuste: rucola selvatica pepata, pomodori maturi succosi, cetrioli croccanti freschi!",
        image: "",
        price: 10.25,
        slug: "leptoceratops-lite",
    },
    {
        name: "Dracorex-Dreams",
        description: "I sogni di un re drago si avverano in questo burger fantastico, maestoso e infuocato! Il Dracorex rappresentava un sognatore - un dinosauro con un'intelligenza leggermente superiore - e il nostro Dracorex-Dreams celebra quella fantasia e quell'ambizione attraverso un burger che è letteralmente fuoco e magia! La polpetta di manzo è infuocata: una miscela di manzo primo taglio, condita generosamente con peperoncino fantasma (uno dei peperoncini più piccanti del mondo), pepe nero fresco macinato, e un pizzico di cayenna. Non è pericolosamente piccante, ma aggiunge un fuoco affascinante che costruisce gradualmente. Il formaggio è un pepper-jack che aggiunge un ulteriore pizzico di calore. Il pane è un focaccia nera tostato leggermente con burro chiarificato e semi di sesamo nero - il nero ricorda la magia dell'oscurità. Le verdure sono tutte piccanti: rucola selvatica pepata, peperoni rossi arrostiti, jalapeños freschi!",
        image: "",
        price: 14.50,
        slug: "dracorex-dreams",
    },
    {
        name: "Gallimimus-Gallop",
        description: "Corri veloce verso questo burger perché il Gallimimus non aspetta e nemmeno tu dovresti! Il Gallimimus era noto per la sua velocità incredibile, e il nostro Gallimimus-Gallop è un burger fast yet flavorful - veloce al palato ma esplosivo nei sapori! La polpetta è cotta velocissimamente su una piastra rovente per mantenere i succhi naturali e creare una crosticina rapidamente - una tecnica che richiede precisione e velocità. La miscela è manzo magro e pancetta per aggiungere sapore senza rallentare l'esperienza. Il formaggio è un cheddar veloce da fondere - scende rapidamente sotto il calore della polpetta appena cotta. Il pane è un panino semplice ma corposo, in grado di assorbire i succhi rapidamente senza dissolversi. Le verdure sono tagliate sottilmente per una masticazione rapida!",
        image: "",
        price: 11.00,
        slug: "gallimimus-gallop",
    },
    {
        name: "Minmi-Marvel",
        description: "Una meraviglia corazzata di sapore e protezione! Il Minmi (un Ankilosauro australiano) rappresenta una meraviglia corazzata della natura, e il nostro Minmi-Marvel celebra questa meraviglia con un burger letteralmente 'protetto' e 'blindato' di sapore! La polpetta di manzo è una meraviglia di succosità - una miscela di manzo wagyu, pancetta affumicata, e un pizzico di guancia di manzo cotta lentamente per aggiungere tenerezza straordinaria. Viene cotta perfettamente. La vera 'corazza' del burger viene dal sistema di protezione di formaggi multipli: uno strato di cheddar invecchiato, uno strato di emmental svizzero, uno strato di smoked gouda, e uno strato di pecorino romano - quattro strati di protezione di formaggio che creano una vera 'corazza' di sapore. Il pane è un pane integrale robusto tostato leggermente, designato per portare il peso della protezione!",
        image: "",
        price: 12.99,
        slug: "minmi-marvel",
    },
    {
        name: "Saltopus-Sublime",
        description: "Sublime ed elegantemente piccolo, il Saltopus-Sublime dimostra che un gusto incredibile può esplodere anche da cose piccole! Questo burger abbraccia il piccolo formato per creare un'esperienza sublime di qualità assoluta. La polpetta è di soli 90 grammi, ma è un concentrato di eccellenza: manzo wagyu A5 giapponese al 100%, stagionato per 35 giorni, condito solo con sale di Maldon e pepe nero fresco. Niente altro - la semplicità dell'eccellenza. Viene cotta su una piastra a 400 gradi per sviluppare una crosticina sublime. Il formaggio è un singolo pezzo di comté francese invecchiato di 36 mesi - un formaggio sublime e complesso. Il pane è un mini panino di segale scura con impasto di lunga fermentazione. Le verdure sono sublime nella loro semplicità: una singola foglia di rucola selvatica di montagna, uno spicchio di pomodoro nero Kumato maturo!",
        image: "",
        price: 9.75,
        slug: "saltopus-sublime",
    },
    {
        name: "Argentinosaurus-Awesome",
        description: "Un burger così grande e impressionante che devi letteralmente staccare le mascelle per mangiarlo! L'Argentinosaurus era il dinosauro più grande mai scoperto, e il nostro Argentinosaurus-Awesome è il nostro burger più gigantesco e incredibile! Questo è il re di tutti i burger - una creazione monumentale designata solo per i veri guerrieri del cibo. La polpetta è massiccia: 350 grammi di una miscela suprema di manzo wagyu, bisonte americano, pancetta di anatra, e fegato di vitello affumicato. Tutti questi ingredienti si combinano per creare una polpetta che è non solo gigantesca, ma incredibilmente complessa nel sapore. Viene cotta su una piastra enorme per sviluppare una crosticina caramellizzata spettacolare. Il formaggio è una cascata: cheddar bianco, provolone affumicato, fontina italiana, gouda olandese, emmental svizzero, pecorino romano - sei formaggi diversi!",
        image: "",
        price: 17.99,
        slug: "argentinosaurus-awesome",
    },
    {
        name: "Supersaurus-Supreme",
        description: "Supremo in ogni singolo aspetto! Il Supersaurus-Supreme è il nostro capolavoro di eccellenza assoluta - un burger super che letteralmente non conosce rivali nel regno preistorico del cibo! Questo è il burger per coloro che capiscono che 'super' non è solo una parola, è uno stato mentale di ricerca dell'eccellenza. La polpetta è una miscela super: manzo wagyu giapponese A5 fuso con bisonte canadese del nord, pancetta di anatra affumicata, e un pizzico di osso di midollo tostato per aggiungere profondità umami incredibile. Viene cotta con precisione scientifica. Il formaggio è un super-combo: tre strati separati di formaggi completamente diversi - cheddar bianco invecchiato 5 anni, brie fresco di capra, e un raro formaggio erborinato di montagna che crea un'esperienza multi-strato incredibile!",
        image: "",
        price: 16.50,
        slug: "supersaurus-supreme",
    },
    {
        name: "Brachiosaurus-Bliss",
        description: "La beatitudine di questo burger è letteralmente alta come il collo del Brachiosaurus - una creazione straordinaria che ti solleva in stati di pura gioia gastronomica! Il Brachiosaurus, con il suo collo infinitamente lungo, rappresenta l'aspirazione verso l'alto, e il nostro Brachiosaurus-Bliss celebra quest'aspirazione attraverso un burger che cresce verticalmente verso il cielo culinario. La polpetta è una meraviglia di succosità: una miscela di manzo prime grade, pancetta affumicata, e spalla di manzo cotta a bassa temperatura per aggiungere tenerezza e ricchezza. Viene cotta perfettamente. L'architettura di questo burger è stratificata verso l'alto: inizia con un pane brioche burroso in basso, poi uno strato di polpetta, poi uno strato di formaggio cheddar fuso, poi uno strato di lattuga verde dolce, poi uno strato di pomodoro succoso, poi uno strato di cipolla caramellata!",
        image: "",
        price: 15.00,
        slug: "brachiosaurus-bliss",
    },
    {
        name: "Diplodocus-Divine",
        description: "Divino e lungo come il Diplodocus! Un burger che letteralmente ti porta in paradiso con ogni singolo morso che prendi! Il Diplodocus, il lungo dinosauro sauropode, ispira questo burger che è una celebrazione della lunghezza, della grazia, e della divinità del sapore. La polpetta di manzo è cotta perfettamente - una miscela di manzo premium, pancetta affumicata, e un pizzico di guancia per tenerezza incredibile. Il formaggio è un trio divino: cheddar invecchiato, smoked gouda, e brie fresco - ogni uno contribuendo una dimensione divina diversa al sapore. Il pane è un pane integrale lungo e elegante fatto con farina bianca di grano antico, farina integrale biologica, e semi di lino - un pane che rispecchia la lunghezza divina del Diplodocus. Le verdure sono scelte per lunghezza e grazia: rucola lunga e pepata, pomodori heirloom affettati in lunghe fette, cipolla rossa affettata in anelli lunghi!",
        image: "",
        price: 14.75,
        slug: "diplodocus-divine",
    },
    {
        name: "Camarasaurus-Champion",
        description: "Il Camarasaurus era il campione dei dinosauri erbivori del Giurassico, ma il nostro Camarasaurus-Champion non è vegetariano - è pura carne campione! Questo burger celebra il tema dell'ironia - un nome di dinosauro erbivoro per un burger carnivoro campeone, un paradosso gastronomico magnifico! La polpetta di manzo è costruita per il campione: una miscela che include manzo premium, pancetta affumicata, e una piccola aggiunta di carne di cacciagione (selvaggina) per aggiungere un sapore selvaggio e campionesco. Viene cotta con precisione campionesca su una piastra rovente. Il formaggio è un formaggio campione - smoked gouda invecchiato per perfezione, che aggiunge profondità e solidità al profilo gustativo. Il pane è un pane campione - fatto con farina biologica di spelto, tostato con burro e erbe fino a diventare dorato e frattagliato!",
        image: "",
        price: 13.50,
        slug: "camarasaurus-champion",
    },
    {
        name: "Apatasaurus-Adventure",
        description: "Un'avventura incredibile di sapori che non dimenticherai mai nella tua vita! Se l'Apatosauro fosse vivo oggi, ti porterebbe direttamente qui per sperimentare questa avventura culinaria straordinaria! L'Apatosauro era un vagabondo del Giurassico, un esploratore di terre e sapori, e il nostro Apatasaurus-Adventure celebra lo spirito di avventura attraverso un burger che è un'escursione attraverso mondi di sapore diversi. La polpetta è una miscela avventurosa: manzo grass-fed, pancetta affumicata di diverse regioni (americana, canadese, italiana), e un pizzico di carne di cinghiale per aggiungere un elemento selvaggio di avventura. Viene cotta con stile avventuroso su carboni caldi per un sapore affumicato profondo. Il formaggio è un avventuroso trio: cheddar invecchiato, emmental svizzero, e un raro formaggio blu di montagna - creando un'armonia internazionale di sapori!",
        image: "",
        price: 13.75,
        slug: "apatasaurus-adventure",
    },
]